Issue #4 | Add new item to db with form and render to list
the-collab-lab/tcl-65-smart-shopping-list pull request #18
Opened 2023-08-21 21:57 UTC by patty-rose

## Description

This PR adds a form to AddItem.jsx to add items to your shopping list with anticipated ordering dates and adds it to the firebase database using addDoc().

## Related Issue

closes #4 

## Acceptance Criteria

UI-related tasks:
- [x] The `Add Item` view displays a form that allows them to enter the name of the item and select how soon they anticipate needing to buy it again. There should be 3 choices for this:
	- “Soon”, corresponding to 7 days
	- “Kind of soon”, corresponding to 14 days
	- “Not soon”, corresponding to 30 days
- [x] The input that accepts the name of the item has a semantic `label` element associated with it
- [x] The user can submit this form with both the mouse and the `Enter` key  
- [x] When the user submits the form, they see a message indicating that the item either was or was not saved to the database.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
![Screenshot 2023-08-21 at 1 17 08 PM](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/101524326/ed38dd6d-b5a6-4a39-bfb0-a034e010fbe7)

### After

https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/101524326/f1da7f26-be43-462b-b2a5-5c8bd1e6a0bf

## Testing Steps / QA Criteria

Using GitHubs preview, click on "Add Item" and then fill out the form and submit it. 
Submitting will be successful when:
- [ ] "Item _____ was saved to the database"
- [ ] if you click on "List" you will see your item added to the list
- [ ] you can also check the Firebase database through the console, and you will be able to find your new item in the database under the "my test list" collection

2023-08-22 14:10 UTC, shannonerhea requested changes
We should add functionality so that when our users submit a new item to their list the form clears the "item name" field so that it is ready to accept another item.

2023-08-24 06:58 UTC, lydiadunning requested changes
When an error occurs in adding a list item, the message that the item has been added to the database still appears.
The try/catch block in addItem is functioning as expected, it displays the error message to the console, but the error doesn't affect setMessage after the addItem function is called from handleSubmit.

2023-08-24 17:51 UTC, isaiahasanchez commented
> We should add functionality so that when our users submit a new item to their list the form clears the "item name" field so that it is ready to accept another item.

Hi, I implemented the changed requested. Please take a look when you get the chance.

2023-08-24 17:52 UTC, isaiahasanchez commented
> When an error occurs in adding a list item, the message that the item has been added to the database still appears. The try/catch block in addItem is functioning as expected, it displays the error message to the console, but the error doesn't affect setMessage after the addItem function is called from handleSubmit.

Hi, I added the error handling! Thanks

2023-08-24 17:53 UTC, isaiahasanchez commented
> When an error occurs in adding a list item, the message that the item has been added to the database still appears. The try/catch block in addItem is functioning as expected, it displays the error message to the console, but the error doesn't affect setMessage after the addItem function is called from handleSubmit.

Hi, I added the error handling! Thanks

2023-08-24 18:48 UTC, lydiadunning commented
As of the current version, the success message only appears when the new item was added successfully to the database.
There is no message if the item is not saved to the database. According to the acceptance criteria, the user should see a message if the item was not saved to the database.

2023-08-24 23:53 UTC, lydiadunning approved these changes
Well written, effective code. A user-facing message displays after both successful and failed attempts to post to firestore.

2023-08-25 01:16 UTC, shannonerhea approved these changes

2023-08-27 02:17 UTC, DwightTheShark approved these changes
Now that the error messages are corrected, should they stay there or should we do something like a setTimeout?  Why or why not?  Can you comment on your choice to use this type of error alerts over others?

2023-08-27 02:17 UTC, merged