Issue #10 | compute next purchase date and record it in db
the-collab-lab/tcl-65-smart-shopping-list pull request #24
Opened 2023-09-12 01:13 UTC by patty-rose

## Description

Created getDaysBetweenDates function in dates.js which calculates amount of days between date last purchased and current date. Updated ListItem.jsx checkbox handler to be more concise, using `item` over multiple parameters. In Firebase.js we updated addItem so it would include the estimated days until next purchase as submitted in the add-item form. Lastly, in Firebase.js we updated updateItem() to use the calculateEstimate function (imported from collab-lab-utils) to calculate the estimated days until next purchase. Finally updating the db with the new estimated next purchase date as well as the new last purchase date.

## Related Issue

closes #10 

## Acceptance Criteria

- [x] When the user purchases an item, the item’s `dateNextPurchased` property is calculated using the `calculateEstimate` function and saved to the Firestore database
  - [x] `dateNextPurchased` is saved as **a date**, not a number
- [x] A `getDaysBetweenDates` function is exported from `utils/dates.js`  and imported into `api/firebase.js`
  - [x] This function takes two JavaScript Dates and return the number of days that have passed between them

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Video Demo:
![Screenshot 2023-09-11 at 6 04 27 PM](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/101524326/6e990daf-b0de-446e-8615-a9677d93af55)

Notice the dateNextPurchased estimate gets smaller, as the calculateEstimate function takes into account the totalPurchases.

## Testing Steps / QA Criteria

-Open the GitHub demo
-create a new list or use an old list
-add an item, remember what you select for "how soon will you buy this again?"
-find that item in the firebase database console and confirm that "estimatedDaysUntilNextPurchase" matches what you input in the form.
-as you click on the checkbox for your item, watch the datNextPurchased estimate get smaller as it takes into account the totalPurchases (click alot!)

2023-09-12 18:51 UTC, shannonerhea requested changes
Getting strange behavior when an items checkbox is clicked twice. Sets dates to current date (see video) Clicking the items checkbox 1, 3, 4 ,5 times does however seem to be doing some sort of math correctly. 

https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/86745260/9ff5e0f7-020f-4387-833e-bdea39498747

2023-09-13 00:05 UTC, patty-rose commented
@shannonerhea @lydiadunning OK, we updated the code and edited the PR to account for this edge-case. Plese reach out if you continue to have questions :)

2023-09-13 05:10 UTC, lydiadunning commented on src/api/firebase.js
> +		(24 * 60 * 60 * 1000); // Convert to Milliseconds;
It might be better to import the ONE_DAY_IN_MILLISECONDS constant here.

2023-09-13 05:54 UTC, lydiadunning requested changes
The site preview behaves the way described in the QA steps

One of the ACs isn't met. 
getDaysBetweenDates: This function takes two JavaScript Dates and returns the number of days that have passed between them.

Currently, getDaysBetweenDates takes one number (representing a Date in seconds) and returns the number of days that have passed between that date and the current date.

2023-09-13 13:53 UTC, shannonerhea approved these changes
Nice Job! Pretty cool feature.

2023-09-14 00:03 UTC, isaiahasanchez commented
> The site preview behaves the way described in the QA steps
> 
> One of the ACs isn't met. getDaysBetweenDates: This function takes two JavaScript Dates and returns the number of days that have passed between them.
> 
> Currently, getDaysBetweenDates takes one number (representing a Date in seconds) and returns the number of days that have passed between that date and the current date.

Hi Lydia we addressed this issue in our latest Push. Thanks

2023-09-14 05:53 UTC, lydiadunning approved these changes
Great changes. The function getDaysBetweenDates fulfills the acceptance criteria, and both it and updateItem seem clearer to read and easier to understand than before the changes.

2023-09-14 05:53 UTC, lydiadunning commented on src/api/firebase.js
> +			new Date(item.dateLastPurchased?.seconds * 1000), // Convert from seconds to milliseconds and then to a Date
There's a firebase method, [.toDate()](https://firebase.google.com/docs/reference/js/v8/firebase.firestore.Timestamp#todate), that converts a firebase timestamp into a Date object.  You could replace `.seconds * 1000` with `.toDate()` if you wanted to here.

2023-09-15 05:22 UTC, mjhcodes approved these changes
Nice work! This issue can be a tricky one, but your code is easy to follow and your decisions all make sense. Thank you as well for adding the **Things To Consider** section to your PR, as the questions I did have were already addressed. :-)

2023-09-15 05:22 UTC, mjhcodes commented on src/api/firebase.js
> +		(24 * 60 * 60 * 1000); // Convert to Milliseconds;
Agreed. It's best to keep these types of values stored as consts and then use them throughout the codebase. It reduces duplication and also helps avoid very pesky bugs.

2023-09-15 05:22 UTC, mjhcodes commented on src/utils/dates.js
> +
It'd be good to include some jsdocs for this function as well to maintain consistency. Something like:

```
/**
 * Calculates the number of days between two given dates, rounded to the nearest integer
 * 
 * @param {Date} startDate
 * @param {Date} endDate
 * @returns {number}
 */
```

2023-09-15 05:22 UTC, mjhcodes commented on src/api/firebase.js
> +	let daysSinceLastPurchase;
Your call, but it looks like you could also use a ternary here:

```
const daysSinceLastPurchase = item.totalPurchases < 2 ?
    item.estimatedDaysUntilNextPurchase : 
    getDaysBetweenDates(new Date(item.dateLastPurchased?.toDate(), new Date());
```

2023-09-17 16:04 UTC, merged