Add Styling
the-collab-lab/tcl-65-smart-shopping-list pull request #40
Opened 2023-09-30 21:46 UTC by lydiadunning

## Description

This code adds styling, both color changes and some limited changes in layout.  I've tried to work within the original app styling, and make changes globally where I can, to get this done quickly. These changes don't style everything, but they're a starting point.

The new colors were added in `--color-contrast` in the index.css file, but to allow them to appear as transparent, I defined the hsl values separately, and referenced them in an `hsl()` :
```
  --contrast-hsl-vals: 18, 85%, 45%;
  --color-contrast: hsl(var(--contrast-hsl-vals));
```
Then, in ListItem.css, I followed the same pattern with hsla, adding an alpha channel for transparency.
```
  --soon-bg: hsla(var(--contrast-hsl-vals), 0.75);
  --kind-of-soon-bg: hsla(var(--contrast-hsl-vals), 0.5);
```
By creating an alternate value for `contrast-hsl-vals` in a media query, color changes and transparency can be applied without any knowledge of the specific color, and changing between light and dark mode only requires changing the value of `--contrast-hsl-vals`.

There are disadvantages to this method.  Color values for the urgency indicators in lists are commented out. Since the colors are derived using transparency, background and text color values can't be compared directly to figure out if there is adequate contrast between them.  It'd be necessary to find the color in a screenshot to do this comparison.

Also added primary and secondary button styling.  

I tried to limit changes to only styling, but also added the list token to the header.

## Changes Remaining

Layout could use improvement.
Header text doesn't fit on narrow mobile view.
Lots of unused color values in the code.
May need to change dark-mode (default) text on the orange background to black.
Fonts.
Probably needs adjustment to meld with other code changes.
More I'm not thinking of.

## Related Issue

Related to 13 - does not close it.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### After

![image](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/71429289/c867a4d5-0f58-420c-a7d7-74ea4799d816)
![image](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/71429289/bc76a3bb-f6bc-4b1e-87fb-34dd029e4836)
![image](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/71429289/4e812ac7-3df5-457d-ac5e-8a1f6bb9e219)
![image](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/71429289/78d3a21b-df30-49fd-b720-041d6833748d)
![image](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/71429289/1bc923dc-dbea-4bd9-9234-1a18ae2c9b13)
![image](https://github.com/the-collab-lab/tcl-65-smart-shopping-list/assets/71429289/c6cd6df1-742c-4e88-a5d8-e1be80b490c8)

## Testing Steps / QA Criteria

Launch the demo, take a look around.  
Switch between light mode and dark mode.
Check at different screen sizes.

2023-09-30 23:41 UTC, shannonerhea requested changes
This is a great start <3 !!!Centering the layout and having the three word token only be displayed once on each page might be good before our design review tomorrow.

2023-10-01 20:17 UTC, lydiadunning commented
I removed the double list-token name. 
After playing around with it, I think centering would look more professional, but I'm having trouble figuring out how to center elements that should be centered without causing unwanted changes. It'll have to wait.

2023-10-01 21:20 UTC, shannonerhea approved these changes

2023-10-02 12:34 UTC, shannonerhea commented
> I removed the double list-token name. After playing around with it, I think centering would look more professional, but I'm having trouble figuring out how to center elements that should be centered without causing unwanted changes. It'll have to wait.
Awesome work!! Mark had mentioned in our meeting that we didn't have to design dark mode due to that being built in to browsers. I noticed on my machine it was defaulting to the dark mode mock-up. Do you want to remove dark mode css, fix the merge conflicts and then merge? I would love to make a branch and help figure out how to center our layout and maybe add a BG image. Thank you for all this cool css :)

2023-10-02 18:02 UTC, merged